CREATE TYPE "InquiryType" AS ENUM (
  'MASS_SACRAMENT',
  'CATECHUMEN_CLASS',
  'FAITH_PARISH_LIFE',
  'FACILITY_RENTAL',
  'WEBSITE_ONLINE',
  'VOLUNTEER_DONATION',
  'OTHER'
);

ALTER TABLE "Inquiry"
ADD COLUMN "inquiryType" "InquiryType" NOT NULL DEFAULT 'OTHER';
