CREATE TYPE "PastoralCouncilRole" AS ENUM (
  'PARISH_PRIEST',
  'ASSISTANT_PRIEST',
  'RELIGIOUS',
  'CHAIRPERSON',
  'VICE_CHAIRMAN_MALE',
  'SECRETARY',
  'DISTRICT_CHIEF_MALE',
  'LITURGY_DEPARTMENT',
  'EDUCATION_YOUTH_DEPARTMENT',
  'SOCIAL_PASTORAL_DEPARTMENT',
  'FINANCE_DEPARTMENT',
  'MISSION_DEPARTMENT',
  'FACILITY_MANAGEMENT_DEPARTMENT',
  'SENIOR_DEPARTMENT',
  'FAMILY_LIFE_ENVIRONMENT_DEPARTMENT',
  'MIDDLE_HIGH_DEPARTMENT',
  'ELEMENTARY_PR_DEPARTMENT',
  'MALE_DISTRICT_1',
  'FEMALE_DISTRICT_1',
  'MALE_DISTRICT_2',
  'FEMALE_DISTRICT_2',
  'MALE_DISTRICT_3',
  'FEMALE_DISTRICT_3',
  'MALE_DISTRICT_4',
  'FEMALE_DISTRICT_4',
  'MALE_DISTRICT_5',
  'FEMALE_DISTRICT_5'
);

ALTER TABLE "PastoralCouncilMember"
  DROP COLUMN "duty",
  ADD COLUMN "role" "PastoralCouncilRole" NOT NULL,
  ALTER COLUMN "phone" DROP NOT NULL;

CREATE UNIQUE INDEX "PastoralCouncilMember_role_key"
  ON "PastoralCouncilMember"("role");
